enum PlatformMethodName {
  startScanningBeacon, stopScanningBeacon, startMonitoringBeacon, stopMonitoringBeacon, stopMonitoringAllEddyStone, restartMonitoringTargetedEddyStones, clearAllTargetedEddyStones
}